### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber" : "1000000002",
  "amount" : 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber" : "1000000002",
  "amount" : 100
}


### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "f20eb22b07e84f65a81e8deaab671f03",
  "accountNumber" : "1000000002",
  "amount" : 100
}

### query transaction
GET http://localhost:8080/transaction/f20eb22b07e84f65a81e8deaab671f03